---
version: '2.4'

services:
  wiremock:
    container_name: wiremock
    image: rodolpheche/wiremock
    volumes:
      - ./../mocks/wiremock:/home/wiremock:rw
      - ./../mocks/extensions:/var/wiremock/extensions:rw
    ports:
      - 8765:8080
    networks:
      - ccd-network
    command: --extensions="com.github.masonm.JwtMatcherExtension"

networks:
  ccd-network:
    external: true
