---
version: '2.4'

services:
  xui:
    image: "my-build:3"
    environment:
      MICROSERVICE: xui_webapp
      PROTOCOL: http
      XUI_ENV: local

      SERVICES_CCD_COMPONENT_API: http://ccd-api-gateway:3453
      SERVICES_CCD_DATA_STORE_API: http://localhost:4452
      SERVICES_DOCUMENTS_API: http://dm-store:8080
      SERVICES_DOCUMENTS_API_V2: http://ccd-case-document-am-api:4455
      SERVICES_S2S: http://service-auth-provider-api:8080
      SERVICES_IDAM_LOGIN_URL: http://localhost:3501
      SERVICES_IDAM_API_URL: http://idam-api:5000
      SERVICES_IDAM_OAUTH_CALLBACK_URL: /oauth2/callback
      SERVICES_IDAM_CLIENT_ID: xui_webapp
      SERVICES_PAYMENTS_URL: http://wiremock:8080
      SERVICES_CCD_CASE_ASSIGNMENT_API: http://manage-case-assignment:4454
      SERVICES_PRD_API: http://wiremock:8080
      SERVICES_ROLE_ASSIGNMENT_API: http://am-role-assignment-service:4096
      HEALTH_ROLE_ASSIGNMENT_API: http://am-role-assignment-service:4096/health
      
      SERVICES_EM_ANNO_API: http://ccd-api-gateway:3453
      REDISCLOUD_URL: http://dummyrediscloudurl

      #real LAUNCH_DARKLY_CLIENT_ID must be set to enable share a case functionality
      LAUNCH_DARKLY_CLIENT_ID: "${XUI_LD_CLIENT_ID:-dummy}"

      FEATURE_REDIS_ENABLED: "false"
      FEATURE_APP_INSIGHTS_ENABLED: "false"
      FEATURE_SECURE_COOKIE_ENABLED: "false"
      FEATURE_WORKALLOCATION_ENABLED: "true"
      FEATURE_ACCESS_MANAGEMENT_ENABLED: "true"
      APPINSIGHTS_INSTRUMENTATIONKEY: fake

      S2S_SECRET: "${BEFTA_S2S_CLIENT_SECRET_OF_XUI_WEBAPP}"
      IDAM_SECRET: "${OAUTH2_CLIENT_XUI}"

      JURISDICTIONS: PUBLICLAW

      SYSTEM_USER_NAME: "dummy"
      SYSTEM_USER_PASSWORD: "dummy"

    ports:
      - 3333:3000
    depends_on:
      idam-api:
        condition: service_started
      ccd-data-store-api:
        condition: service_started
    networks:
      - ccd-network

networks:
  ccd-network:
    external: true
